version: '3.2'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        volumes:
            - ./.build/rabbitmq/etc/:/etc/rabbitmq/
            - ./.build/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.build/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: "unique-erlang-cookie"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
        ports:
            - "5672:5672"
            - "15672:15672"
        restart: always
volumes:
    elasticseach-data-01:
        driver: local
networks:
    elastic:
        driver: bridge
