version: '3.2'
services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "13306:3306"
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
      - ./data/sync:/var/sync
      - ./data/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
volumes:
  elasticseach-data-01:
    driver: local
networks:
  elastic:
    driver: bridge
